# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Thorfile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ritsu}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pramook Khungurn"]
  s.date = %q{2010-04-17}
  s.default_executable = %q{ritsu}
  s.description = %q{A code generation system that facilitates building C/C++ software with the help of CMake and Doxygen}
  s.email = %q{dragonmeteor@gmail.com}
  s.executables = ["ritsu"]
  s.extra_rdoc_files = [
    "README.md",
     "Thorfile",
     "VERSION"
  ]
  s.files = [
    "README.md",
     "Thorfile",
     "VERSION",
     "bin/ritsu",
     "lib/ritsu.rb",
     "lib/ritsu/block.rb",
     "lib/ritsu/external_library.rb",
     "lib/ritsu/project.rb",
     "lib/ritsu/project_generator.rb",
     "lib/ritsu/project_generators.rb",
     "lib/ritsu/project_generators/default_generator.rb",
     "lib/ritsu/project_generators/default_generator_files/Thorfile.erb",
     "lib/ritsu/project_generators/default_generator_files/meta/project.rb.erb",
     "lib/ritsu/src_file.rb",
     "lib/ritsu/src_files.rb",
     "lib/ritsu/src_files/cpp_file.rb",
     "lib/ritsu/src_files/executable_cmake_lists.rb",
     "lib/ritsu/src_files/header_file.rb",
     "lib/ritsu/src_files/project_cmake_lists.rb",
     "lib/ritsu/src_files/shared_library_cmake_lists.rb",
     "lib/ritsu/src_files/static_library_cmake_lists.rb",
     "lib/ritsu/src_files/target_cmake_lists.rb",
     "lib/ritsu/src_files/templated_src_file.rb",
     "lib/ritsu/target.rb",
     "lib/ritsu/targets.rb",
     "lib/ritsu/targets/executable.rb",
     "lib/ritsu/targets/shared_library.rb",
     "lib/ritsu/targets/static_library.rb",
     "lib/ritsu/template.rb",
     "lib/ritsu/template_policies.rb",
     "lib/ritsu/thors.rb",
     "lib/ritsu/thors/default_thor.rb",
     "lib/ritsu/utility.rb",
     "lib/ritsu/utility/accessors.rb",
     "lib/ritsu/utility/check_upon_add_set.rb",
     "lib/ritsu/utility/file_robot.rb",
     "lib/ritsu/utility/files.rb",
     "lib/ritsu/utility/instance_dependencies.rb",
     "lib/ritsu/utility/instance_set.rb",
     "lib/ritsu/utility/platform.rb",
     "lib/ritsu/utility/simple_io.rb",
     "lib/ritsu/utility/single_instance.rb",
     "lib/ritsu/utility/strings.rb"
  ]
  s.homepage = %q{http://lab.moekaku.com}
  s.rdoc_options = ["--charset=UTF-8", "--title", "Ritsu", "--main", "README.md", "--line-numbers", "--inline-source"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ritsu}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A code generation system that facilitates building C/C++ software with the help of CMake and Doxygen}
  s.test_files = [
    "test/ritsu/block_test.rb",
     "test/ritsu/external_library_test.rb",
     "test/ritsu/project_generators/default_generator_test.rb",
     "test/ritsu/project_test.rb",
     "test/ritsu/src_file_test.rb",
     "test/ritsu/src_files/cpp_file_test.rb",
     "test/ritsu/src_files/executable_cmake_lists_test.rb",
     "test/ritsu/src_files/header_file_test.rb",
     "test/ritsu/src_files/project_cmake_lists_test.rb",
     "test/ritsu/src_files/shared_library_cmake_lists_test.rb",
     "test/ritsu/src_files/static_library_cmake_lists_test.rb",
     "test/ritsu/src_files/target_cmake_lists_test.rb",
     "test/ritsu/target_test.rb",
     "test/ritsu/targets/executable_test.rb",
     "test/ritsu/targets/shared_library_test.rb",
     "test/ritsu/targets/static_library_test.rb",
     "test/ritsu/utility/accessors_test.rb",
     "test/ritsu/utility/check_upon_add_set_test.rb",
     "test/ritsu/utility/file_robot_test.rb",
     "test/ritsu/utility/strings_test.rb",
     "test/test_helpers.rb",
     "test/ritsu",
     "test/ritsu/block_test",
     "test/ritsu/block_test/output",
     "test/ritsu/block_test/static",
     "test/ritsu/project_generators",
     "test/ritsu/project_generators/default_generator_test",
     "test/ritsu/project_generators/default_generator_test/output",
     "test/ritsu/project_generators/default_generator_test/static",
     "test/ritsu/src_files",
     "test/ritsu/src_files/cpp_file_test",
     "test/ritsu/src_files/cpp_file_test/output",
     "test/ritsu/src_files/cpp_file_test/static",
     "test/ritsu/src_files/executable_cmake_lists_test",
     "test/ritsu/src_files/executable_cmake_lists_test/output",
     "test/ritsu/src_files/executable_cmake_lists_test/static",
     "test/ritsu/src_files/header_file_test",
     "test/ritsu/src_files/header_file_test/output",
     "test/ritsu/src_files/header_file_test/static",
     "test/ritsu/src_files/project_cmake_lists_test",
     "test/ritsu/src_files/project_cmake_lists_test/output",
     "test/ritsu/src_files/project_cmake_lists_test/static",
     "test/ritsu/src_files/shared_library_cmake_lists_test",
     "test/ritsu/src_files/shared_library_cmake_lists_test/output",
     "test/ritsu/src_files/shared_library_cmake_lists_test/static",
     "test/ritsu/src_files/static_library_cmake_lists_test",
     "test/ritsu/src_files/static_library_cmake_lists_test/output",
     "test/ritsu/src_files/static_library_cmake_lists_test/static",
     "test/ritsu/targets",
     "test/ritsu/utility",
     "test/ritsu/utility/file_robot_test",
     "test/ritsu/utility/file_robot_test/output",
     "test/ritsu/utility/file_robot_test/static"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0.13.4"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_development_dependency(%q<jeweler>, [">= 1.4.0"])
      s.add_development_dependency(%q<yard>, [">= 0.5.3"])
      s.add_development_dependency(%q<maruku>, [">= 0.5.9"])
    else
      s.add_dependency(%q<thor>, [">= 0.13.4"])
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<jeweler>, [">= 1.4.0"])
      s.add_dependency(%q<yard>, [">= 0.5.3"])
      s.add_dependency(%q<maruku>, [">= 0.5.9"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0.13.4"])
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<jeweler>, [">= 1.4.0"])
    s.add_dependency(%q<yard>, [">= 0.5.3"])
    s.add_dependency(%q<maruku>, [">= 0.5.9"])
  end
end

