require File.expand_path(File.dirname(__FILE__) + "/cuda/src_files/cu_file")
require File.expand_path(File.dirname(__FILE__) + "/cuda/src_files/target_cmake_lists")
require File.expand_path(File.dirname(__FILE__) + "/cuda/project")
require File.expand_path(File.dirname(__FILE__) + "/cuda/external_library.rb")
require File.expand_path(File.dirname(__FILE__) + "/cuda/targets/library.rb")
require File.expand_path(File.dirname(__FILE__) + "/cuda/target.rb")