require File.expand_path(File.dirname(__FILE__) + '/utility/strings')
require File.expand_path(File.dirname(__FILE__) + '/utility/accessors')
require File.expand_path(File.dirname(__FILE__) + '/utility/instance_set')
require File.expand_path(File.dirname(__FILE__) + '/utility/simple_io')
require File.expand_path(File.dirname(__FILE__) + '/utility/file_robot')
require File.expand_path(File.dirname(__FILE__) + '/utility/check_upon_add_set')
require File.expand_path(File.dirname(__FILE__) + '/utility/files')
require File.expand_path(File.dirname(__FILE__) + '/utility/platform')