require 'rubygems'
require 'active_support'

require File.dirname(__FILE__) + '/ritsu/external_library'
require File.dirname(__FILE__) + '/ritsu/project'
require File.dirname(__FILE__) + '/ritsu/target'
require File.dirname(__FILE__) + '/ritsu/src_file'
require File.dirname(__FILE__) + '/ritsu/block'
require File.dirname(__FILE__) + '/ritsu/template'
require File.dirname(__FILE__) + '/ritsu/project_generator'

require File.dirname(__FILE__) + '/ritsu/template_policies'
require File.dirname(__FILE__) + '/ritsu/targets'
require File.dirname(__FILE__) + '/ritsu/src_files'
require File.dirname(__FILE__) + '/ritsu/utility'
require File.dirname(__FILE__) + '/ritsu/project_generators'
require File.dirname(__FILE__) + '/ritsu/thors'